POST http://localhost:8000/sing_up HTTP/1.1
content-type: application/json

{
    "email": "asdasdsdf@gmail.com",
    "password": "ASdasd!3124"
}

###

POST http://localhost:8000/sing_in HTTP/1.1
content-type: application/json

{
    "email": "asdasdsdf@gmail.com",
    "password": "ASdasd!3124"
}

###
POST http://localhost:8000/create_channel HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjY0MjYxNjIsImlhdCI6MTcyNjM5MDE2MiwiaXNzIjoiYXV0aC1zZXJ2aWNlIiwic3ViIjozLCJ0eXBlIjoiYWNjZXNzIn0.GghXcgkWomxrEt7acL6YY5EJ_dmcwz6i1L55KyOBgLrVTQD2v6Q_Mx6oJHZt8vF3D72TEt6PnE6CI0cHirp3DQ

{
    "name": "test1",
    "description": "do consectetur deserunt dolor",
    "public": true
}

###
Get http://localhost:8000/get_channel/23 HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjY0MjYxNjIsImlhdCI6MTcyNjM5MDE2MiwiaXNzIjoiYXV0aC1zZXJ2aWNlIiwic3ViIjozLCJ0eXBlIjoiYWNjZXNzIn0.GghXcgkWomxrEt7acL6YY5EJ_dmcwz6i1L55KyOBgLrVTQD2v6Q_Mx6oJHZt8vF3D72TEt6PnE6CI0cHirp3DQ
